module.id=badea-correspondence
module.aliases=badea-correspondence

module.title=BADEA Presidency Correspondence
module.description=Alfresco repository extension for BADEA Presidency correspondence

module.version=1.0.0
module.repo.version.min=26.1